[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "protocol"
path = "src/lib.rs"

[[bin]]
name = "cli"
path = "src/cli/main.rs"

[dependencies]
async-std = { version = "1.9.0", features = ["attributes", "tokio1"] }
async-trait = "0.1.51"
multi-party-ecdsa ={ git = "https://github.com/ZenGo-X/multi-party-ecdsa"}
zk-paillier = { version = "0.4.2", default-features = false }
# sha2 = "0.9"
anyhow = "1.0.53"
thiserror = "1.0.30"
tokio = { version = "1.16", features = ["macros","fs","rt-multi-thread","io-util"] }
futures = "0.3"
round-based = { version = "0.1.4", features = ["dev"] }
serde_json = "1.0"
structopt = "0.3"
rocket = { version = "0.5.0-rc.1", default-features = false, features = ["json"] }
surf = "2"
serde = { version = "1.0", features = ["derive"] }
async-sse = "5"
curv-kzen = { version = "0.9", default-features = false }
sp-keyring = { package = "sp-keyring", git = "https://github.com/paritytech/substrate/", branch = "master" }
subxt = { git = "https://github.com/paritytech/subxt.git" }
codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive", "full", "bit-vec"] }
parity-scale-codec-derive = "2.3.1"
common = { path = "../../crypto/common", default-features = false }


[dependencies.scale-info]
default-features = false
features = ['derive']
version = '1.0'

[dependencies.paillier]
version = "0.4.2"
package = "kzen-paillier"
default-features = false
