# Opinionated whitespace and tabs. The most important of these are imports and width settings.
# https://rust-lang.github.io/rustfmt

# version-related
use_try_shorthand=true   # replace any `try!` (2015 Rust) with `?`
edition          ="2018"

# misc formatting
match_block_trailing_comma=true # include comma in match blocks after '}'
use_field_init_shorthand  =true # struct initialization short {x: x} -> {x}

# reduce whitespace
newline_style="Unix" # not auto, we won the culture war. \n over \r\n

# width settings: everything to 100
max_width           =100   # default: 100
use_small_heuristics="Max" # don't ever newline short of `max_width`.

# tabs and spaces (use spaces)
hard_tabs=false # (default: false) use spaces over tabs
