[profile.release]
panic='unwind'

[workspace]
members=[
  'crypto/centralized-keygen',
  'crypto/signing-client',
  'crypto/c-manager',
  'crypto/shared-crypto',
  'crypto/shared-types',
  'crypto/testing-utils',
  'node/*',
  'pallets/*',
  'runtime',
  # 'alice-send',
  # 'subxttest'
]
