[profile.release]
panic = 'unwind'

[workspace]
members = [
    'crypto/centralized-keygen',
    'crypto/signing-client',
    'crypto/testing-utils',
    'node/*',
    'pallets/*',
    'runtime',
	# 'alice-send',
    # 'subxttest'
]
