[profile.release]
panic = 'unwind'

[workspace]
members = [
    'crypto/signing-grpc',
    'crypto/protocol',
    'crypto/signing-client',
    'crypto/testing-user-clients',
	'crypto/testing-utils',
    'node/*',
    'pallets/*',
    'runtime',
	# 'alice-send',
    # 'subxttest'
]
