[package]
name      ="pallet-attestation"
version   ="0.3.0-rc.1"
authors   =['Entropy Cryptography <engineering@entropy.xyz>']
homepage  ='https://entropy.xyz/'
license   ='AGPL-3.0-or-later'
repository='https://github.com/entropyxyz/entropy-core'
edition   ='2021'
publish   =false

[dependencies]
codec             ={ package="parity-scale-codec", version="3.6.3", default-features=false, features=["derive"] }
scale-info        ={ version="2.11", default-features=false, features=["derive"] }
log               ={ version="0.4.22", default-features=false }
frame-support     ={ version="38.0.0", default-features=false }
frame-system      ={ version="38.0.0", default-features=false }
sp-io             ={ version="38.0.0", default-features=false }
sp-core           ={ version="34.0.0", default-features=false }
sp-runtime        ={ version="39.0.1", default-features=false }
sp-staking        ={ version="36.0.0", default-features=false }
frame-benchmarking={ version="38.0.0", default-features=false, optional=true }
sp-std            ={ version="14.0.0", default-features=false }
pallet-session    ={ version="38.0.0", default-features=false, optional=true }
rand_chacha       ={ version="0.3", default-features=false }

pallet-parameters={ version="0.3.0-rc.1", path="../parameters", default-features=false }
entropy-shared={ version="0.3.0-rc.1", path="../../crates/shared", features=[
  "wasm-no-std",
], default-features=false }
pallet-staking-extension={ version="0.3.0-rc.1", path="../staking", default-features=false }
tdx-quote="0.0.1"

[dev-dependencies]
pallet-session                 ={ version="38.0.0", default-features=false }
pallet-staking                 ={ version="38.0.0", default-features=false }
pallet-balances                ={ version="39.0.0", default-features=false }
pallet-bags-list               ={ version="37.0.0", default-features=false }
pallet-timestamp               ={ version="37.0.0", default-features=false }
sp-npos-elections              ={ version="34.0.0", default-features=false }
frame-election-provider-support={ version="38.0.0", default-features=false }
pallet-staking-reward-curve    ={ version="12.0.0" }
tdx-quote                      ={ version="0.0.1", features=["mock"] }
rand_core                      ="0.6.4"

[features]
default=['std']
runtime-benchmarks=['frame-benchmarking', 'tdx-quote/mock', 'pallet-session']
std=[
  'frame-benchmarking/std',
  'frame-support/std',
  'frame-system/std',
  'log/std',
  'pallet-staking-extension/std',
  'pallet-balances/std',
  'pallet-parameters/std',
  'sp-io/std',
  "sp-runtime/std",
  "codec/std",
  "rand_chacha/std",
]
try-runtime=['frame-support/try-runtime']
