[package]
name      ="pallet-attestation"
version   ="0.1.0"
authors   =['Entropy Cryptography <engineering@entropy.xyz>']
homepage  ='https://entropy.xyz/'
license   ='AGPL-3.0-or-later'
repository='https://github.com/entropyxyz/entropy-core'
edition   ='2021'
publish   =false

[dependencies]
codec        ={ package="parity-scale-codec", version="3.6.3", default-features=false, features=["derive"] }
scale-info   ={ version="2.11", default-features=false, features=["derive"] }
log          ={ version="0.4.22", default-features=false }
frame-support={ version="29.0.0", default-features=false }
frame-system ={ version="29.0.0", default-features=false }
tdx-quote    ={ git="https://github.com/entropyxyz/tdx-quote" }

entropy-shared={ version="0.2.0", path="../../crates/shared", features=[
  "wasm-no-std",
], default-features=false }
pallet-staking-extension={ version="0.2.0", path="../staking", default-features=false }

[features]
default=['std']
# runtime-benchmarks=['frame-benchmarking']
std=[
  # 'frame-benchmarking/std',
  'frame-support/std',
  'frame-system/std',
  'log/std',
  'pallet-staking-extension/std',
]
try-runtime=['frame-support/try-runtime']
