[package]
name   ="testing-utils"
version="0.1.0"
edition="2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp-keyring        ="6.0.0"
project-root      ="0.2.2"
sp-core           ={ version="6.0.0", default-features=false }
env_logger        ="0.9.0"
log               ="0.4.14"
which             ="4.0.2"
subxt             ={ git="https://github.com/paritytech/subxt.git" }
parity-scale-codec="3.0.0"
