[package]
name   ="testing-utils"
version="0.1.0"
edition="2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subxt             ={ package="subxt", git="https://github.com/paritytech/subxt.git", tag="v0.32.1" }
sp-keyring        ="24.0.0"
project-root      ="0.2.2"
sp-core           ={ version="21.0.0", default-features=false }
env_logger        ="0.9.0"
log               ="0.4.14"
which             ="4.0.2"
parity-scale-codec="3.0.0"
lazy_static       ="1.4.0"
hex-literal       ="0.3.4"
entropy-shared    ={ path="../shared" }
