[package]
name = "signing-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", default-features = false, features = ["json"]}
reqwest = { version = "0.9", default-features = false }
serde_json = "1.0"
uuid = { version = "0.8", features = ["v4"] }
parity-scale-codec = "2.3.1"
common = { path = "../../crypto/common", default-features = false }
subxt = { git = "https://github.com/paritytech/subxt.git" }
multi-party-ecdsa ={ git = "https://github.com/ZenGo-X/multi-party-ecdsa"}
curv-kzen = { version = "0.9", default-features = false }
anyhow = "1.0.53"
futures = "0.3"
tokio = { version = "1.16", features = ["macros","fs","rt-multi-thread","io-util"] }
serde = { version = "1.0", features = ["derive"] }


[features]
default = ['std']
std = []
