[package]
name      ='pallet-registry'
version   ='0.2.0-rc.1'
authors   =['Entropy Cryptography <engineering@entropy.xyz>']
homepage  ='https://entropy.xyz/'
license   ='AGPL-3.0-or-later'
repository='https://github.com/entropyxyz/entropy-core'
edition   ='2021'
publish   =false

[package.metadata.docs.rs]
targets=['x86_64-unknown-linux-gnu']

[dependencies]
codec     ={ package="parity-scale-codec", version="3.6.3", default-features=false, features=["derive"] }
scale-info={ version="2.11", default-features=false, features=["derive"] }
log       ={ version="0.4.22", default-features=false }

frame-benchmarking={ version="29.0.0", default-features=false, optional=true }
frame-support     ={ version="29.0.0", default-features=false }
frame-system      ={ version="29.0.0", default-features=false }
pallet-authorship ={ version="29.0.0", default-features=false }
pallet-session    ={ version="29.0.0", default-features=false }
pallet-staking    ={ version="29.0.0", default-features=false }
sp-core           ={ version="29.0.0", default-features=false }
sp-runtime        ={ version="32.0.0", default-features=false }
sp-std            ={ version="14.0.0", default-features=false }

entropy-shared={ version="0.2.0-rc.1", path="../../crates/shared", features=[
  "wasm-no-std",
], default-features=false }
pallet-programs={ version="0.2.0-rc.1", path="../programs", default-features=false }
pallet-staking-extension={ version="0.2.0-rc.1", path="../staking", default-features=false }

[dev-dependencies]
frame-election-provider-support={ version="29.0.0", default-features=false }
pallet-bags-list               ={ version="28.0.0", default-features=false }
pallet-balances                ={ version="29.0.0", default-features=false }
pallet-staking-reward-curve    ={ version="11.0.0" }
pallet-timestamp               ={ version="28.0.0", default-features=false }
sp-io                          ={ version="31.0.0", default-features=false }
sp-npos-elections              ={ version="27.0.0", default-features=false }
sp-staking                     ={ version="27.0.0", default-features=false }

[features]

std=[
  "sp-npos-elections/std",
  "sp-runtime/std",
  "sp-std/std",
  'codec/std',
  'frame-benchmarking/std',
  'frame-support/std',
  'frame-system/std',
  'log/std',
  'pallet-balances/std',
  'pallet-programs/std',
  'pallet-staking-extension/std',
  'scale-info/std',
]
default=['std']
runtime-benchmarks=[
  'frame-benchmarking',
  'pallet-programs/runtime-benchmarks',
  'pallet-staking-extension/runtime-benchmarks',
]
try-runtime=['frame-support/try-runtime']
