[package]
name      ='pallet-programs'
version   ='0.0.10'
authors   =['Entropy Cryptography <engineering@entropy.xyz>']
homepage  ='https://entropy.xyz/'
license   ='AGPL-3.0-or-later'
repository='https://github.com/entropyxyz/entropy-core'
edition   ='2021'
publish   =false

[package.metadata.docs.rs]
targets=['x86_64-unknown-linux-gnu']

[dependencies]
codec     ={ package="parity-scale-codec", version="3.6.3", default-features=false, features=["derive"] }
scale-info={ version="2.1", default-features=false, features=["derive"] }
log       ={ version="0.4.0", default-features=false }

frame-benchmarking={ version="25.0.0", default-features=false, optional=true }
frame-support     ={ version="25.0.0", default-features=false }
frame-system      ={ version="25.0.0", default-features=false }
sp-io             ={ version="27.0.0", default-features=false }
sp-runtime        ={ version="28.0.0", default-features=false }
sp-staking        ={ version="23.0.0", default-features=false }
sp-std            ={ version="12.0.0", default-features=false }

entropy-shared={ path="../../crates/shared", default-features=false, features=["wasm-no-std"] }

[dev-dependencies]
pallet-balances={ version="25.0.0" }
sp-core        ={ version="25.0.0", default-features=false }

[features]
default=['std']
runtime-benchmarks=['frame-benchmarking']
std=[
  "scale-info/std",
  "sp-io/std",
  "sp-runtime/std",
  'codec/std',
  'frame-benchmarking/std',
  'frame-support/std',
  'frame-system/std',
  'log/std',
]
try-runtime=['frame-support/try-runtime']
