[package]
name      ='pallet-staking-extension'
version   ='0.3.0-rc.1'
authors   =['Entropy Cryptography <engineering@entropy.xyz>']
homepage  ='https://entropy.xyz/'
license   ='AGPL-3.0-or-later'
repository='https://github.com/entropyxyz/entropy-core'
edition   ='2021'
publish   =false

[package.metadata.docs.rs]
targets=['x86_64-unknown-linux-gnu']

[dependencies]
codec      ={ package="parity-scale-codec", version="3.6.3", default-features=false, features=["derive"] }
scale-info ={ version="2.11", default-features=false, features=["derive"] }
log        ={ version="0.4.22", default-features=false }
serde      ={ version="1.0.213", default-features=false }
rand_chacha={ version="0.3", default-features=false }

frame-benchmarking= { version = "38.0.0", default-features = false, optional = true }
frame-support     = { version = "38.0.0", default-features = false }
frame-system      = { version = "38.0.0", default-features = false }
pallet-session    = { version = "38.0.0", default-features = false }
pallet-staking    = { version = "38.0.0", default-features = false }
sp-core           = { version = "34.0.0", default-features = false }
sp-runtime        = { version = "39.0.1", default-features = false }
sp-staking        = { version = "36.0.0", default-features = false }
sp-std            = { version = "14.0.0", default-features = false }
sp-consensus-babe = { version = "0.40.0", default-features = false }

pallet-parameters={ version="0.3.0-rc.1", path="../parameters", default-features=false }
entropy-shared={ version="0.3.0-rc.1", path="../../crates/shared", features=[
  "wasm-no-std",
], default-features=false }

# We only use this in benchmarks and tests. Since the benches don't run with the `test` feature we need to
# import it here _and_ as a `dev-dependency`.
tdx-quote={ version="0.0.1", features=["mock"], optional=true }

[dev-dependencies]
frame-election-provider-support= { version = "38.0.0", default-features = false }
pallet-bags-list               = { version = "37.0.0", default-features = false }
pallet-balances                = { version = "39.0.0", default-features = false }
pallet-staking-reward-curve    = { version = "12.0.0" }
pallet-timestamp               = { version = "37.0.0", default-features = false }
sp-io                          = { version = "38.0.0", default-features = false }
sp-npos-elections              = { version = "34.0.0", default-features = false }

rand_core="0.6.4"
tdx-quote={ version="0.0.1", features=["mock"] }

[features]
default=['std']
runtime-benchmarks=['frame-benchmarking', 'tdx-quote']
std=[
  "sp-npos-elections/std",
  "sp-staking/std",
  "sp-std/std",
  "sp-io/std",
  'codec/std',
  'frame-benchmarking/std',
  'frame-support/std',
  'frame-system/std',
  'log/std',
  'pallet-balances/std',
  'pallet-parameters/std',
  'pallet-session/std',
  'pallet-staking/std',
  'scale-info/std',
  'sp-consensus-babe/std',
  'sp-runtime/std',
  "rand_chacha/std",
]
try-runtime=['frame-support/try-runtime']
