[package]
name       ='pallet-staking-extension'
version    ='3.0.0'
description='FRAME pallet template for defining custom runtime logic.'
authors    =['Substrate DevHub <https://github.com/substrate-developer-hub>']
homepage   ='https://substrate.dev'
edition    ='2018'
license    ='Unlicense'
publish    =false
repository ='https://github.com/substrate-developer-hub/substrate-node-template/'

[package.metadata.docs.rs]
targets=['x86_64-unknown-linux-gnu']

[dependencies.codec]
default-features=false
features        =['derive']
package         ='parity-scale-codec'
version         ='3.2.1'

[dependencies.frame-benchmarking]
default-features=false
git             ='https://github.com/paritytech/substrate.git'
optional        =true
branch          ="polkadot-v0.9.32"

[dependencies.frame-support]
default-features=false
git             ='https://github.com/paritytech/substrate.git'
branch          ="polkadot-v0.9.32"

[dependencies.frame-system]
default-features=false
git             ='https://github.com/paritytech/substrate.git'
branch          ="polkadot-v0.9.32"

[dependencies.scale-info]
default-features=false
features        =['derive']
version         ='2.0.1'

[dev-dependencies.sp-core]
default-features=false
git             ='https://github.com/paritytech/substrate.git'
branch          ="polkadot-v0.9.32"
version         ="6.0.0"

[dev-dependencies.sp-io]
default-features=false
git             ='https://github.com/paritytech/substrate.git'
branch          ="polkadot-v0.9.32"
version         ="6.0.0"

[dependencies]
pallet-staking   ={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.32" }
sp-runtime       ={ version="6.0.0", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.32" }
sp-std           ={ package="sp-std", git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.32", default-features=false }
sp-core          ={ package="sp-core", git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.32", default-features=false }
sp-consensus-babe={ version="0.10.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.32" }
log              ={ version="0.4.0", default-features=false }
pallet-session   ={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.32" }
sp-staking       ={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.32" }
entropy-shared   ={ path="../../crypto/shared", default-features=false }
serde            ={ version="1.0.147", default-features=false }

[dev-dependencies]
pallet-balances                ={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.32" }
pallet-timestamp               ={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.32" }
frame-election-provider-support={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.32" }
pallet-session                 ={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.32" }
sp-staking                     ={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.32" }
pallet-staking-reward-curve    ={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.32" }
pallet-bags-list               ={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.32" }
sp-npos-elections              ={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.32" }

[features]
default=['std']
runtime-benchmarks=['frame-benchmarking']
std=[
  'codec/std',
  'scale-info/std',
  'frame-support/std',
  'frame-system/std',
  'sp-runtime/std',
  "sp-std/std",
  'pallet-staking/std',
  'pallet-session/std',
  'pallet-balances/std',
  'frame-benchmarking/std',
  "sp-npos-elections/std",
  "sp-staking/std",
  "sp-consensus-babe/std",
  'log/std',

]
try-runtime=['frame-support/try-runtime']
