[package]
name = "etp-lindell17"
version = "0.1.0"
edition = "2021"

[dependencies]
#num-bigint = { version = "0.4", features = ["rand"] }
rand = "0.8"
k256 = { version = "0.9.6", features = ["ecdsa", "arithmetic"] }

[features]
std = [  ]
default = [ ]
