@startuml node_signing_flow
title node signing flow
alice -> receiving_api : sends tx (incl.ComProof)
receiving_api -> other_nodes: broadcasts tx
receiving_api -> signing_node: broadcasts tx
other_nodes -> signing_node : sends shard 
signing_node -> alice : PoK               /' added this line '/
alice -> signing_node : Decommit          /' added this line '/      
signing_node -> alice : sends signed tx
@enduml
