@startuml Communication-Sequence
Alice -> AnyNode : request Signer-ID
AnyNode -> Alice : provide Signer-ID
group DKG
    Alice -> Signer : Commitment + PoK 
    Signer -> Alice : PoK
    Alice -> Signer : Decommit + Paillier-proofs + other
    Signer -> all_nodes : distribute keys (trust issue)
    Signer -> onchain_storage :(optional: Cond.Set)
end
group Signing
    Alice -> Signer : Commitment + PoK 
    Signer -> Alice : PoK
    Signer -> all_nodes : broadcast: request shards
    all_nodes -> Signer : supply shards
    Alice -> Signer : Decommit
    Signer -> Alice : c_3
    Signer -> onchain_storage: update chain
end
@enduml