// Copyright (C) 2023 Entropy Cryptography Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_programs`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 33.0.0
//! DATE: 2024-11-08, STEPS: `5`, REPEAT: `2`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Jesses-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/entropy
// benchmark
// pallet
// --chain
// dev
// --pallet=pallet_programs
// --extrinsic=*
// --steps=5
// --repeat=2
// --header=.maintain/AGPL-3.0-header.txt
// --output=./runtime/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_programs`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_programs::WeightInfo for WeightInfo<T> {
	/// Storage: `Programs::Programs` (r:1 w:1)
	/// Proof: `Programs::Programs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Programs::OwnedPrograms` (r:1 w:1)
	/// Proof: `Programs::OwnedPrograms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `o` is `[0, 10]`.
	fn set_program(_o: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `214`
		//  Estimated: `3679`
		// Minimum execution time: 23_000_000 picoseconds.
		Weight::from_parts(26_554_140, 0)
			.saturating_add(Weight::from_parts(0, 3679))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Programs::Programs` (r:1 w:1)
	/// Proof: `Programs::Programs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Programs::OwnedPrograms` (r:1 w:1)
	/// Proof: `Programs::OwnedPrograms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `p` is `[0, 250]`.
	/// The range of component `o` is `[0, 10]`.
	fn remove_program(p: u32, o: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `353 + o * (1 ±0) + p * (32 ±0)`
		//  Estimated: `3842 + o * (1 ±0) + p * (32 ±0)`
		// Minimum execution time: 22_000_000 picoseconds.
		Weight::from_parts(28_023_735, 0)
			.saturating_add(Weight::from_parts(0, 3842))
			// Standard Error: 11_641
			.saturating_add(Weight::from_parts(103_353, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(Weight::from_parts(0, 1).saturating_mul(o.into()))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(p.into()))
	}
}
