
//! Autogenerated weights for `pallet_free_tx`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-09-07, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/entropy
// benchmark
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=pallet_free_tx
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=./runtime/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_free_tx`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_free_tx::WeightInfo for WeightInfo<T> {
	// Storage: FreeTx FreeCallsPerEra (r:1 w:0)
	// Storage: FreeTx FreeCallsRemaining (r:1 w:1)
	// Storage: Staking CurrentEra (r:1 w:0)
	fn try_free_call() -> Weight {
		(18_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: unknown [0x3a7472616e73616374696f6e5f6c6576656c3a] (r:1 w:1)
	// Storage: FreeTx FreeCallsPerEra (r:0 w:1)
	fn set_max_free_calls_per_era() -> Weight {
		(4_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// TODO
	fn give_one_time_calls() -> Weight {
		(0 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// TODO
	fn set_rechargable_call_count() -> Weight {
		(0 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}
