[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
scale-info = { version = '1.0', default-features = false, features = ['derive'] }
