[package]
name   ="shared-crypto"
version="0.1.0"
edition="2021"

[dependencies]
serde ={ version="1.0", features=["derive"] }
uuid  ={ version="1.1.2", features=["serde", "v4", "js"] }
anyhow="1.0.53"
