name: build and upload apple-aarch64
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-env:
    name: build/upload 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      - run:
            ./scripts/setup-debian.sh
      - run:
            cargo build --target aarch64-apple-darwin --release