name: apple-x86_64-darwin
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-env:
    name: build/upload 
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: 
            PATH=/opt/homebrew/bin:$PATH ./scripts/setup-macos.sh 
      - run:
            PATH=/opt/homebrew/bin:$PATH ./scripts/build-and-upload.sh x86_64-apple-darwin 
            