---
name: "Build and test"
on: ["push"]

jobs:
  code-paths-changed:
    name: Detect whether code changes have been made
    runs-on: ubuntu-latest
    outputs:
      run_tests: ${{ steps.filter.outputs.changes_detected }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for relevant changes
        id: filter
        run: |
          ## If this is the first commit on a branch, then the default behaviour of github.event.before is to show the previous ref as
          ## repeated zeroes, as the previous ref is null
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          elif git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E "^(node/|crates/|pallets/|runtime/)"; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

  node-test:
    needs: code-paths-changed
    runs-on: core-build-runner
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4
      - name: Increase swap
        if: needs.code-paths-changed.outputs.run_tests == 'true'
        run: |
          sudo swapoff -a
          sudo dd if=/dev/zero of=/swapfile bs=1G count=8
          sudo chmod 0600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          grep Swap /proc/meminfo
      - name: Install dependencies
        if: needs.code-paths-changed.outputs.run_tests == 'true'
        uses: ./.github/actions/install-dependencies/
      - name: Build entropy-protocol nodejs package
        if: needs.code-paths-changed.outputs.run_tests == 'true'
        run: |
          cd crates/protocol
          make build-nodejs-testing
          cd nodejs-test
          yarn
          cd ../../..
      - name: Run `cargo build && cargo test`
        run: |
          pushd node
          cargo build --all-targets --release -j $(nproc)
          cargo test --all-targets --release
          yarn --cwd ../crates/protocol/nodejs-test test
          cargo test -p entropy-tss --release --features=test_helpers -F wasm_test test_wasm
          cargo build --all-targets --release --features="server production" -j $(nproc)
      - name: Skip tests when no code changes have been made
        if: needs.code-paths-changed.outputs.run_tests == 'false'
        run: |
          echo "Skipping tests as no code changes have been made"
