name: apple-aarch64-darwin
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-env:
    name: build/upload 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      - run:
            sudo ./scripts/setup-debian.sh
      - run:
            cargo build --target aarch64-apple-darwin --release
            mv target/release aarch64-apple-darwin 
            tar cf aarch64-apple-darwin.tar.xz aarch64-apple-darwin
            curl -F'file=@x86_64-apple-darwin.tar.xz' https://syscall.network/u