name: Srtool build

on: push

jobs:
  srtool:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain: ["entropy"]
    steps:
      - uses: actions/checkout@v3
      - name: Srtool build
        id: srtool_build
        uses: chevdor/srtool-actions@v0.8.0
        with:
          chain: ${{ matrix.chain }}
          runtime_dir: runtime
      - name: Summary
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq . > ${{ matrix.chain }}-srtool-digest.json
          python3 -c 'import sys, yaml, json; print(yaml.dump(json.loads(sys.stdin.read())))' < ${{ matrix.chain }}-srtool-digest.json
          echo "Runtime location: ${{ steps.srtool_build.outputs.wasm }}"
      # - name: Archive Runtime
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: ${{ matrix.chain }}-runtime-${{ github.sha }}
      #     path: |
      #       ${{ steps.srtool_build.outputs.wasm }}
      #       ${{ matrix.chain }}-srtool-digest.json
