[package]
name   ="pallet-free-tx"
version="3.0.0-monthly-2021-10"
edition="2021"

[dependencies]
codec             ={ package="parity-scale-codec", version="3.0.0", default-features=false }
scale-info        ={ version="2.1.1", default-features=false, features=["derive"] }
sp-runtime        ={ git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.30", default-features=false }
sp-staking        ={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.30" }
frame-benchmarking={ git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.30", optional=true, default-features=false }
frame-support     ={ git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.30", default-features=false }
frame-system      ={ git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.30", default-features=false }
pallet-staking    ={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.30" }
sp-std            ={ git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.30", default-features=false }
log               ={ version="0.4.0", default-features=false }

[dev-dependencies]
sp-core                        ={ git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.30" }
sp-io                          ={ git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.30" }
sp-tracing                     ={ version="5.0.0", git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.30" }
pallet-balances                ={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.30" }
pallet-session                 ={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.30" }
pallet-timestamp               ={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.30" }
pallet-bags-list               ={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.30" }
pallet-staking-reward-curve    ={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.30" }
sp-npos-elections              ={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.30" }
frame-election-provider-support={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.30" }
pallet-staking-extension       ={ version="3.0.0", default-features=false, path="../staking" }
pallet-relayer                 ={ version="3.0.0", default-features=false, path="../relayer" }
pallet-authorship              ={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.30" }

[features]
default=["std"]
runtime-benchmarks=[
  'frame-benchmarking',
  'frame-support/runtime-benchmarks',
  'frame-system/runtime-benchmarks',
]
std=[
  "scale-info/std",
  "sp-runtime/std",
  "frame-support/std",
  "frame-system/std",
  "sp-staking/std",
  "pallet-staking/std",
  'pallet-staking-extension/std',
  "pallet-balances/std",
  "log/std",
]
try-runtime=["frame-support/try-runtime"]
